### ISSUE TITLE
Demo throws Internal server error

### ISSUE THREAD

**Issue by cniry** [OndrejSlamecka/CoolMS#2]
http://coolmsdemo.slamecka.cz/ throws Internal server error

**Comment by OndrejSlamecka** [comment]
The issue is with the menu designer. If I recall correctly the problem appears when you try to remove the whole menu structure or in some other edge case (users never recreated the problem on my other projects running CoolMS).

Unfortunately I can't make the time for this project now and fix the issue. So there are two options:
- I'll help you identify the issue and you'll fix it
- I'll remove the demo
